name: TripAdvisorDownload
channels:
  - conda-forge
  - anaconda
  - tensorflow
  - simpleitk
  - defaults
dependencies:
  - python=3.9
  - filetype
  - opencv
  - pandas
  - requests
  - tqdm
  - pyquery
  - pillow
