name: TripAdvisorDownload
channels:
  - conda-forge
  - anaconda
  - tensorflow
  - simpleitk
  - defaults
dependencies:
  - aom=3.5.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - colorama=0.4.6
  - cryptography=39.0.2
  - cssselect=1.2.0
  - expat=2.5.0
  - ffmpeg=5.1.2
  - filetype=1.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeglut=3.2.2
  - freetype=2.12.1
  - gettext=0.21.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - graphite2=1.3.13
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - harfbuzz=6.0.0
  - icu=70.1
  - idna=3.4
  - intel-openmp=2023.0.0
  - jasper=4.0.0
  - krb5=1.20.1
  - lcms2=2.15
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libdeflate=1.18
  - libffi=3.4.2
  - libglib=2.74.1
  - libhwloc=2.9.0
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libogg=1.3.4
  - libopencv=4.7.0
  - libopus=1.3.1
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libsqlite=3.40.0
  - libtiff=4.5.0
  - libvorbis=1.3.7
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzlib=1.2.13
  - lxml=4.9.2
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mkl=2022.1.0
  - msys2-conda-epoch=20160418
  - numpy=1.24.2
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.1.0
  - pandas=1.5.3
  - pcre2=10.40
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.40.0
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - py-opencv=4.7.0
  - pycparser=2.21
  - pyopenssl=23.1.0
  - pyquery=2.0.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2023.2
  - qt-main=5.15.8
  - requests=2.28.2
  - setuptools=67.6.0
  - six=1.16.0
  - svt-av1=1.4.1
  - tbb=2021.8.0
  - tk=8.6.12
  - tqdm=4.65.0
  - tzdata=2023b
  - ucrt=10.0.22621.0
  - urllib3=1.26.15
  - vc=14.3
  - vs2015_runtime=14.34.31931
  - wheel=0.40.0
  - win_inet_pton=1.1.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
